namespace Bank.Logic.Abstractions;

// do not edit this file

public interface IAccount
{
    AccountSettings Settings { get; set; }
    IReadOnlyList<ITransaction> GetTransactions();
    bool TryAddTransaction(ITransaction transaction);
    double GetBalance();
}
